#!/usr/bin/env bash
cd /c/git/igsayi/python-scripts-iqserver
python iq_apps.py
python iq_components.py
python iq_components-Release-stage.py
python iq_licensedata.py
python iq_reports-history.py
python iq_reports.py
python iq_policy_waivers.py
python iq_component_waivers.py